### ISSUE TITLE
Can't change ProgressBar color

### ISSUE THREAD

**Issue by jmrobles** [voghDev/ProgressButtonView#5]
In my app, the spin color is white and the background is white too, we need to change the color of the spin.

**Comment by voghDev** [comment]
Ok, I'll find a way to change the progressBar color :) thanks for reporting the issue

**Comment by voghDev** [comment]
Now you can apply a color filter to the progress bar drawable, like this:

    progressButtonView.setIndeterminateDrawableColorFilter(0xFFFF00FF,
                android.graphics.PorterDuff.Mode.MULTIPLY);

There's sample code [here](https://github.com/voghDev/ProgressButtonView/blob/master/sample/src/main/java/es/voghdev/progressbuttonview/sample/CustomProgressBarActivity.java)

Gonna make it setable via XML too, and release a lib version.

**Comment by voghDev** [comment]
lib version `0.7.8` just released. ProgressBar can now be tinted in various ways:

[programatically](https://github.com/voghDev/ProgressButtonView/blob/master/sample/src/main/java/es/voghdev/progressbuttonview/sample/CustomProgressBarActivity.java)

[via XML](https://github.com/voghDev/ProgressButtonView/blob/master/sample/src/main/res/layout/activity_custom_progress_bar_xml.xml)

Let me know if this suits your needs :)

**Comment by voghDev** [comment]
Definitely fixed. Just tried it in [Pokepromo](https://play.google.com/store/apps/details?id=com.pokepromo.app) app and it works.
